// Package conformance holds the cross-implementation conformance harness. The
// vectors it checks (docs/conformance/*.json) are generated by an INDEPENDENT
// implementation (a Python reference using an RFC 8785 library), so these tests
// prove the Go implementation and an independent one agree bit-for-bit on every
// deterministic surface a third party must reproduce to interoperate:
//
//   - intent digests            (docs/conformance/intent-digests.json)
//   - receipt signing inputs    (docs/conformance/receipt-signing-inputs.json)
//   - envelope suite signing    (docs/conformance/suite-signing-inputs.json)
//   - status-list decoding      (docs/conformance/status-list-decode.json)
//   - JCS canonical forms       (internal/jcs/testdata/golden.json — checked there)
//
// A third party can implement the SPT-Txn spec and validate against these files
// without our code. Drift in any deterministic transform fails this harness.
package conformance
